baseurl = "https://ruanhao.github.io/"
languageCode = "zh-cn"
title = "Hao Ruan"
copyright = "&copy; Copyright Hao Ruan"
theme = "vienna"

[permalinks]
    post = "/blog/:year/:month/:day/:filename/"

[params]
    # Social accounts. Link to these accounts are displayed in the header and footer.

    # twitter = "ruanhao"
    github = "ruanhao"
    linkedin = "ruanhao1116"
    # stackoverflow = "1267982"
    facebook = "ruanhao1116"
    # instagram = "ruanhao"
    # Disqus shortname
    disqus = "ruanhao"
    # Google Analytics API key.
    ga_api_key = "UA-109678845-1"
    # Mixpanel API key.
    author = "Hao Ruan"
    avatar = "/images/avatar.jpg"
    # contact = "ruanhao1116@gmail.com"
    bio = "software engineer @ Shanghai"
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "用简单的文字记录生活与技术"
    themecolor = "#333" # Defines the tab color in Chrome for Android.
    description = "Hao Ruan 技术博客"
